# Generated by Django 5.1.1 on 2024-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.DateField()),
                ('temperatura_media', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Meteo',
        ),
    ]
